Unit test for books_controller and book_modle
vareal-vietnam/bookstore pull request #14
Opened 2019-07-17 02:46 UTC by canhdinhvareal

2019-07-17 03:26 UTC, mrcuong84 commented on spec/controllers/books_controller_spec.rb
> +        expect(assigns(:book).description).to equal(@book.description)
should use eql rather than equal

2019-07-17 03:26 UTC, mrcuong84 commented on spec/controllers/books_controller_spec.rb
> +        expect(assigns(:book).comment).to equal(@book.comment)
should use eql rather than equal

2019-07-17 03:26 UTC, mrcuong84 commented on spec/controllers/books_controller_spec.rb
> +        expect(flash[:danger]).to eql(I18n.t('not_found'))
should use eql rather than equal

2019-07-18 08:08 UTC, hieunguyentrung requested changes

2019-07-18 08:08 UTC, hieunguyentrung commented on spec/controllers/books_controller_spec.rb
>          expect(assigns(:books).count).to equal(@book_ids.count)
Phần này nên so sánh với `Book.count`, và ở dưới là `Book.all.pluck(:id)`. Bên trên cũng vậy, mình đang cần so sánh với dữ liệu từ db thực tế chứ không phải cái vừa tạo ra.

2019-07-18 08:14 UTC, hieunguyentrung requested changes

2019-07-18 08:14 UTC, hieunguyentrung commented on spec/controllers/books_controller_spec.rb
>          expect(assigns(:books).count).to equal(1)
Có thể bỏ qua phần 1 cuốn sách này, bên dưới bao hàm luôn rồi. Logic hiện tại cũng chưa có gì đặc biệt khi chỉ có 1 cuốn sách nên không cần thiết phải test.

2019-07-18 08:14 UTC, hieunguyentrung commented on spec/controllers/books_controller_spec.rb
> +        expect(assigns(:book).images).to match_array(@book.images)
Nếu là quan hệ cơ bản đã khai báo trong model rồi thì không cần test, cái này mình có test ở quan hệ trong model rồi.

2019-07-18 10:02 UTC, closed without merging