Implement and test book request list
vareal-vietnam/bookstore pull request #64
Opened 2019-08-01 09:35 UTC by banguyenvareal

2019-08-01 09:46 UTC, dinhnguyencanh commented on app/assets/stylesheets/custom.scss
> +.paginate {
delete it!

2019-08-01 09:46 UTC, dinhnguyencanh commented on app/views/book_requests/index.html.erb
> +              <%= User.find(book_request.user_id).name %></p>
use delegate

2019-08-02 01:55 UTC, dinhvareal requested changes

2019-08-02 01:55 UTC, dinhnguyencanh commented on app/assets/stylesheets/custom.scss
> +
extra blank line end of file

2019-08-02 01:55 UTC, dinhnguyencanh commented on app/views/book_requests/index.html.erb
> +              <%= User.find(book_request.user_id).name %></p>
remove

2019-08-02 01:55 UTC, dinhnguyencanh commented on app/views/book_requests/index.html.erb
> -            <p class="book-request-title"><%= book_request.name %></p>
Why did you remove book request title

2019-08-02 02:16 UTC, dinhvareal approved these changes

2019-08-02 02:48 UTC, mrcuong84 approved these changes

2019-08-02 10:02 UTC, hieunguyentrung approved these changes

2019-08-02 10:02 UTC, merged