Remember me
vareal-vietnam/bookstore pull request #66
Opened 2019-08-05 01:21 UTC by mrcuong84

2019-08-05 06:18 UTC, banguyenvareal commented on spec/controllers/sessions_controller_spec.rb
> +        post :create, params: {
`should use shared_context`

2019-08-05 07:44 UTC, mrcuong84 commented on spec/controllers/sessions_controller_spec.rb
> +        post :create, params: {
already fix

2019-08-05 07:48 UTC, banguyenvareal approved these changes

2019-08-06 02:10 UTC, hieunguyentrung requested changes

2019-08-06 02:10 UTC, hieunguyentrung commented on app/models/user.rb
> +  def create_token_and_update_remember_digest
`generate_remember_token!`

2019-08-06 02:10 UTC, hieunguyentrung commented on app/helpers/sessions_helper.rb
> +  def remember_and_assign_cookies(user)
`remember_user`

2019-08-06 02:10 UTC, hieunguyentrung commented on app/helpers/sessions_helper.rb
> +  def forget_and_delete_cookies(user)
`forget_user`

2019-08-06 02:10 UTC, hieunguyentrung commented on app/models/user.rb
> +  def remove_remember_digest_value
`remove_remember_digest`

2019-08-06 02:10 UTC, hieunguyentrung commented on app/models/user.rb
> +    update_attribute(:remember_digest, nil)
`update_attribute(remember_digest: nil)`

2019-08-06 02:10 UTC, hieunguyentrung commented on spec/controllers/sessions_controller_spec.rb
> +    context 'invalid param input' do
`invalid params input `

2019-08-06 02:13 UTC, hieunguyentrung requested changes

2019-08-06 02:13 UTC, hieunguyentrung commented on app/helpers/sessions_helper.rb
> +  def assign_user_to_session(user)
`save_user_to_session`

2019-08-06 02:13 UTC, hieunguyentrung commented on app/helpers/sessions_helper.rb
> +  def find_and_assign_by_cookies
`find_and_assign_by_cookie`

2019-08-07 01:29 UTC, hieunguyentrung approved these changes

2019-08-07 01:49 UTC, merged