Update some ui
vareal-vietnam/bookstore pull request #67
Opened 2019-08-05 03:19 UTC by banguyenvareal

2019-08-05 03:47 UTC, mrcuong84 commented on app/views/book_requests/edit.html.erb
> +<h1>Update Your Book Request </h1>
i18n

2019-08-05 03:47 UTC, mrcuong84 commented on app/views/book_requests/new.html.erb
>  <h1>Create Book Request </h1>
i18n

2019-08-05 04:07 UTC, mrcuong84 approved these changes

2019-08-06 01:20 UTC, dinhvareal approved these changes

2019-08-06 01:24 UTC, dinhnguyencanh commented on app/views/users/book_requests/_list.html.erb
> +          <a href="<%= edit_user_book_request_path current_user, book_request %>"><span class="glyphicon glyphicon-edit"></span></a>
use link_to

2019-08-06 02:34 UTC, hieunguyentrung requested changes

2019-08-06 02:34 UTC, hieunguyentrung commented on app/views/users/book_requests/_list.html.erb
> +<% book_requests&.each do |book_request| %>
Limit use `&`. Remove it. !

2019-08-06 02:34 UTC, hieunguyentrung commented on app/controllers/users/book_requests_controller.rb
> +      @book_requests = User.find(params[:user_id])
Breake into `book_user` method to find user.

2019-08-06 02:34 UTC, hieunguyentrung commented on app/views/books/_book_list.html.erb
> +<% @books.each do |book| %>
Don't use instance variable inside the partial view.

2019-08-06 02:34 UTC, hieunguyentrung commented on app/views/books/_book_list.html.erb
> +<% @books.each do |book| %>
`_list.hmtl.erb` is enough.

2019-08-06 02:34 UTC, hieunguyentrung commented on app/views/layouts/_header.html.erb
> +          <li><%= link_to "Book Requests", book_requests_path %></li>
i18n

2019-08-06 02:34 UTC, hieunguyentrung commented on app/views/users/show.html.erb
> +        <li><%= link_to "Book Requests", user_book_requests_path(current_user)%></li>
i18n.

2019-08-06 06:39 UTC, hieunguyentrung approved these changes

2019-08-06 06:39 UTC, merged