Fix bug 21 book pagination
vareal-vietnam/bookstore pull request #68
Opened 2019-08-06 08:56 UTC by dinhnguyencanh

2019-08-06 09:14 UTC, banguyenvareal commented on app/views/books/index.html.erb
> +  <%= render partial: 'books/list', locals: { books: @books } %>
`list` is enough

2019-08-06 09:22 UTC, banguyenvareal approved these changes

2019-08-06 09:48 UTC, hieunguyentrung requested changes

2019-08-06 09:48 UTC, hieunguyentrung commented on app/helpers/pagination_helper.rb
> +  def collect(collection, page, per_page)
`paginate_collection`

2019-08-07 01:29 UTC, hieunguyentrung approved these changes

2019-08-07 01:29 UTC, merged