implement SignUP
vareal-vietnam/bookstore pull request #8
Opened 2019-07-11 09:51 UTC by mrcuong84

2019-07-15 02:30 UTC, dinhvareal commented on app/assets/stylesheets/custom.scss
> +.avatar{
.custom-avatar

2019-07-15 02:30 UTC, dinhvareal commented on app/assets/stylesheets/custom.scss
> +  width:90px;
width: 150px;

2019-07-15 02:30 UTC, canhdinhvareal commented on app/views/users/new.html.erb
> +      <%= render 'kaminari/error_messages' %>
move error_message to shared

2019-07-15 02:40 UTC, mrcuong84 commented on app/views/users/new.html.erb
> +      <%= render 'kaminari/error_messages' %>
resolved

2019-07-15 02:40 UTC, mrcuong84 commented on app/assets/stylesheets/custom.scss
> +.avatar{
already fix

2019-07-15 02:41 UTC, mrcuong84 commented on app/assets/stylesheets/custom.scss
> +  width:90px;
resolved

2019-07-15 02:41 UTC, mrcuong84 commented on app/views/users/new.html.erb
> +      <%= render 'kaminari/error_messages' %>
resolved

2019-07-15 03:03 UTC, hieunguyentrung commented on app/controllers/sessions_controller.rb
> +      flash[:success] = 'Dang nhap thanh cong!'
I18n ?

2019-07-15 03:03 UTC, hieunguyentrung commented on Gemfile
> +gem 'carrierwave',             '1.2.2'
Please remove.

2019-07-15 03:35 UTC, mrcuong84 commented on app/controllers/sessions_controller.rb
> +      flash[:success] = 'Dang nhap thanh cong!'
resolved

2019-07-15 03:36 UTC, mrcuong84 commented on Gemfile
> +gem 'carrierwave',             '1.2.2'
already removed

2019-07-15 05:31 UTC, hieunguyentrung requested changes

2019-07-15 05:31 UTC, hieunguyentrung commented on app/controllers/users_controller.rb
> +    flash[:danger] = 'User khong ton tai, moi ban dang nhap'
I18n ?

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/layouts/application.html.erb
> +      <% flash.each do |message_type, message| %>
Duplicate

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/sessions/new.html.erb
> +      <%= f.submit "Log in", class: "btn btn-primary" %>
I18n.

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/sessions/new.html.erb
> +    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
I18n.

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/shared/_error_messages.html.erb
> +      The form contains <%= pluralize(@user.errors.count, "error") %>.
I18n.

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/shared/_error_messages.html.erb
> +    <% @user.errors.full_messages.each do |msg| %>
Change `msg` to `message`.

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/users/new.html.erb
> +        <%= f.label :phone %> <p><i>(10 chữ số định dạng 09xxx.....)</i></p>
I18n.

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/users/new.html.erb
> +        <%= f.label :password %> <p><i>(nhập ít nhất 6 ký tự)</i></p>
I18n.

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/users/new.html.erb
> +        <%= f.submit "Create my account", class: "btn btn-primary" %>
I18n.

2019-07-15 05:31 UTC, hieunguyentrung commented on app/views/users/new.html.erb
> +        <%= f.label :password_confirmation, "Password Confirmation" %>
I18n.

2019-07-15 05:31 UTC, hieunguyentrung commented on db/migrate/20190711013707_create_users.rb
> +      t.string :phone
`NOT NULL`

2019-07-15 05:31 UTC, hieunguyentrung commented on config/routes.rb
> +  get '/signup', to: 'users#new'
Just using `/users/new` from `users` resource. Don't need `/signup` path.

2019-07-15 05:31 UTC, hieunguyentrung commented on config/routes.rb
> +  get 'sessions/new'
This code is redundant.

2019-07-15 05:31 UTC, hieunguyentrung commented on config/routes.rb
> +  get 'users/new'
This code is redundant.

2019-07-15 05:31 UTC, hieunguyentrung commented on config/routes.rb
> +  post '/login', to: 'sessions#create'
Using default `POST /users`.

2019-07-15 05:31 UTC, hieunguyentrung commented on config/routes.rb
> +  delete '/logout',  to: 'sessions#destroy'
Using default path when using `resource :users`.

2019-07-15 05:31 UTC, hieunguyentrung commented on config/routes.rb
> +  post '/signup',  to: 'users#create'
Using default path when using `resource :users`.

2019-07-15 05:31 UTC, hieunguyentrung commented on db/migrate/20190711013707_create_users.rb
> +      t.string :password_digest
`NOT NULL`

2019-07-15 05:55 UTC, canhdinhvareal commented on app/controllers/sessions_controller.rb
> +      flash[:success] = 'Đăng nhập thành công'
I18n

2019-07-15 05:55 UTC, canhdinhvareal commented on app/controllers/sessions_controller.rb
> +      flash[:warning] = 'Nhập sai Số điện thoại/password'
I18n

2019-07-15 05:55 UTC, canhdinhvareal commented on app/views/sessions/new.html.erb
> +      <%= f.label :phone %>
you can change :phone to t('.phone') for the label

2019-07-15 05:55 UTC, canhdinhvareal commented on app/views/sessions/new.html.erb
> +      <%= f.label :password %>
Use I18n

2019-07-15 05:55 UTC, canhdinhvareal commented on app/views/users/new.html.erb
> +        <%= f.label :name %>
Use I18n for the label

2019-07-15 05:55 UTC, canhdinhvareal commented on app/views/users/new.html.erb
> +        <%= f.label :address %>
Use I18n for the label

2019-07-16 01:59 UTC, canhdinhvareal commented on app/views/users/index.html.erb
> +      <div class="col-sm-3"><img src="https://media.istockphoto.com/vectors/bookstore-logo-template-design-logo-open-book-vector-id1088265598" alt="Img" class="avatar"></div>
img src="<%= user.avatar %>"

2019-07-16 10:14 UTC, hieunguyentrung approved these changes

2019-07-16 10:14 UTC, merged